#!/bin/bash

#PBS -P <Project>
#PBS -N bamstats
#PBS -l select=1:ncpus=16:mem=60GB
#PBS -l walltime=02:00:00
#PBS -M <your_email>@sydney.edu.au
#PBS -m e
#PBS -q defaultQ
#PBS -o ./Logs/bamstats.o
#PBS -e ./Logs/bamstats.e
#PBS -J 1-3

module load samtools/1.10
module load singularity/3.7.0

# to run: qsub bamsummaries.pbs 

# edit these to match your project (specify full path)
config=/project/Munchkins/Scripts/Configs/Munchkins.config #where is your config file
bams=/scratch/Munchkins/Bams # have to bind mount for Singularity, cannot read /scratch or /project

NCPUS=16
sample=$(awk -v taskID=$PBS_ARRAY_INDEX '$1==taskID {print $2}' $config)
bam=${bams}/${sample}.final.bam
flags=${bams}/${sample}.flagstats

rm -r ${flags}

# run flagstats, collate summary report with multiQC (singularity image)

samtools flagstat -@ $NCPUS -O tsv $bam > $flags

singularity exec -B ${bams}:$HOME \
        /project/Munchkins/Apps/multiqc_1.9--py_1.sif \
        multiqc . --profile-runtime \
        --filename ${sample}_multiqc_finalbam \
        -o ${bams}
