#!/bin/bash

#PBS -P <Project>
#PBS -N BQSR
#PBS -l select=1:ncpus=16:mem=80GB
#PBS -l walltime=24:00:00
#PBS -M <your email>@sydney.edu.au
#PBS -m e
#PBS -q defaultQ
#PBS -o ./Logs/bqsr.o
#PBS -e ./Logs/bqsr.e
#PBS -J 1-3

# edit PBS variables for projectID, your email address, number of jobs to be run in parallel (number of samples in your config file).

# to run: qsub bqsr.pbs
## run BQSR with population-level variant dataset

# edit these to match your project (specify full path)
Project=
config=/project/${Project}/Scripts/Configs/Munchkins.config
ref=/project/${Project}/Reference/felCat9.0.fasta
known=/project/${Project}/Reference/felis_catus.vcf.gz

#### DON'T EDIT BELOW THIS LINE ####

module load gatk/4.1.9.0
module load samtools/1.10

Bams=/scratch/${Project}/Bams
sample=$(awk -v taskID=$PBS_ARRAY_INDEX '$1==taskID {print $2}' $config)
logdir=/project/${Project}/Scripts/Logs/BQSR
log=${logdir}/${sample}_bqsr.log

mkdir -p $logdir

# Base quality score recalibration with GATK, 2 steps:

# make bqsr recal tables
gatk BaseRecalibrator \
        --java-options "-Xmx20g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" \
        -R $ref \
        -I ${Bams}/${sample}.dedup.sorted.bam  \
        -known-sites ${known} \
        -O ${Bams}/${sample}.recal_data.table >> $log 2>&1

# apply recal tables to bams
gatk ApplyBQSR \
        --java-options "-Xmx6G -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" \
        -R $ref \
        -I ${Bams}/${sample}.dedup.sorted.bam  \
        --bqsr-recal-file ${Bams}/${sample}.recal_data.table \
        --create-output-bam-index \
        -O ${Bams}/${sample}.final.bam >> $log 2>&1
